spring:
  server.tomcat.uri-encoding: UTF-8
  datasource:
    platform: h2
    jdbc-url: jdbc:h2:mem://localhost/~/shortening
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
#            sql:
              BasicBinder: TRACE
server:
  port: 8081